Traceback (most recent call last):
  File "/home/yang1641/PINNACLE/pinnacle/generate_input.py", line 94, in read_data
    G = nx.read_edgelist(G_f)
  File "/home/yang1641/.conda/envs/pinnacle/lib/python3.8/site-packages/networkx/utils/decorators.py", line 845, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 5", line 3, in argmap_read_edgelist_1
    import gzip
  File "/home/yang1641/.conda/envs/pinnacle/lib/python3.8/site-packages/networkx/utils/decorators.py", line 191, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/bell/yang1641/exome/data/PINNACLE/networks/global_ppi_edgelist.txt'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "pinnacle/train.py", line 79, in <module>
    ppi_data, mg_data, edge_attr_dict, celltype_map, tissue_neighbors, ppi_layers, metagraph = read_data(args.G_f, args.ppi_dir, args.mg_f, hparams['feat_mat'])
  File "/home/yang1641/PINNACLE/pinnacle/generate_input.py", line 101, in read_data
    raise e2
  File "/home/yang1641/PINNACLE/pinnacle/generate_input.py", line 99, in read_data
    G = nx.read_edgelist(G_f, delimiter=',')
  File "<class 'networkx.utils.decorators.argmap'> compilation 5", line 3, in argmap_read_edgelist_1
    import gzip
  File "/home/yang1641/.conda/envs/pinnacle/lib/python3.8/site-packages/networkx/utils/decorators.py", line 191, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/bell/yang1641/exome/data/PINNACLE/networks/global_ppi_edgelist.txt'